### ISSUE TITLE
memcahed modules meet  too many values to unpack

### ISSUE THREAD

**Issue by WangWenchao** [lincolnloop/salt-stats#4]
Thx your modules, but I met the belowing

```
minion-1.demo.com:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1161, in _thread_return
        return_data = func(*args, **kwargs)
      File "/var/cache/salt/minion/extmods/modules/memcached.py", line 32, in stats
        _, name, val = line.split(' ')
    ValueError: too many values to unpack
```

**Comment by ipmb** [comment]
What is the output of `echo "stats" | nc 127.0.0.1 11211` on your memcached server?
